version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: shortlink-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: shortlink_root_123456
      MYSQL_DATABASE: shortlink
      MYSQL_USER: shortlink
      MYSQL_PASSWORD: shortlink123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: shortlink-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 短链接API服务
  shortlink-api:
    image: nodesire77/shorturl_api:latest
    container_name: shortlink-api
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # 基本配置
      - API_TOKEN=${API_TOKEN:-your-secure-api-token-here}
      - BASE_URL=${BASE_URL:-http://localhost:2282}
      - SHORT_CODE_LENGTH=${SHORT_CODE_LENGTH:-6}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # 数据库配置
      - DB_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=shortlink
      - MYSQL_PASSWORD=shortlink123456
      - MYSQL_DATABASE=shortlink
      
      # Redis配置
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CACHE_TTL=3600
    ports:
      - "2282:2282"
    volumes:
      - api_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2282/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: shortlink-nginx
    restart: unless-stopped
    depends_on:
      - shortlink-api
    ports:
      - "80:80"
    volumes:
      - ./nginx-full.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  api_logs:
    driver: local

networks:
  default:
    name: shortlink-network
