version: '3.8'

services:
  shortlink-api:
    build: .
    container_name: shortlink-production-api
    restart: unless-stopped
    environment:
      - API_TOKEN=${API_TOKEN}
      - BASE_URL=${BASE_URL:-http://localhost:2282}
      - SHORT_CODE_LENGTH=${SHORT_CODE_LENGTH:-6}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "2282:2282"
    volumes:
      - data:/app/data
      - logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2282/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: shortlink-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - logs:/var/log/nginx
    depends_on:
      - shortlink-api
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
    driver: local
  logs:
    driver: local
