version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: shortlink-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: shortlink123456
      MYSQL_DATABASE: shortlink
      MYSQL_USER: shortlink
      MYSQL_PASSWORD: shortlink123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shortlink-network

  # Redis缓存（可选）
  redis:
    image: redis:7-alpine
    container_name: shortlink-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - shortlink-network

  # Python后端API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shortlink-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://shortlink:shortlink123456@mysql:3306/shortlink
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=shortlink
      - DB_USER=shortlink
      - DB_PASSWORD=shortlink123456
      - REDIS_URL=redis://redis:6379/0
      - HOST=0.0.0.0
      - PORT=9848
      - DEBUG=False
      - SECRET_KEY=your-production-secret-key-change-this
      - DEFAULT_DOMAIN=localhost:8848
      - CORS_ORIGINS=["http://localhost:8848", "http://0.0.0.0:8848"]
    ports:
      - "9848:9848"
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    depends_on:
      - mysql
      - redis
    networks:
      - shortlink-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9848/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node.js前端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shortlink-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://0.0.0.0:9848
      - VITE_DEFAULT_DOMAIN=localhost:8848
    ports:
      - "8848:8848"
    depends_on:
      - backend
    networks:
      - shortlink-network

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: shortlink-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - shortlink-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  shortlink-network:
    driver: bridge
