version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: shortlink-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: shortlink_root_123456
      MYSQL_DATABASE: shortlink
      MYSQL_USER: shortlink
      MYSQL_PASSWORD: shortlink123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: shortlink-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 短链接API服务
  shortlink-api:
    image: nodesire77/shorturl_api:latest
    container_name: shortlink-api
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # 基本配置
      - API_TOKEN=${API_TOKEN:-$(openssl rand -hex 32)}
      - BASE_URL=${BASE_URL:-http://localhost:2282}
      - SHORT_CODE_LENGTH=${SHORT_CODE_LENGTH:-6}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # 数据库配置
      - DB_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=shortlink
      - MYSQL_PASSWORD=shortlink123456
      - MYSQL_DATABASE=shortlink
      
      # Redis配置
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CACHE_TTL=3600
    ports:
      - "2282:2282"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2282/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
  redis_data:
