services:
  shortlink:
    image: nodesire77/shorturl_api:all-in-one
    container_name: shortlink-single
    restart: unless-stopped
    environment:
      - API_TOKEN=${API_TOKEN}
      - BASE_URL=${BASE_URL:-http://localhost:2282}
      - SHORT_CODE_LENGTH=${SHORT_CODE_LENGTH:-6}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "2282:2282"
    volumes:
      - shortlink_mysql:/var/lib/mysql
      - shortlink_redis:/var/lib/redis
      - shortlink_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2282/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  shortlink_mysql:
  shortlink_redis:
  shortlink_logs:
